version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 front-end: # name of the first service
  build: ./front-end/ # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port mapping  
 api: # name of the second service
  build: ./api/
  ports:
  - "3000:3000" #specify ports mapping
  links:
  - database:27017 # link this service to the database service
 
 database: # name of the third service
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding
